name: health-check-app
services:
  - name: health-check-service
    source_dir: /
    github:
      repo: your-username/app-health-check
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080 